#!/usr/bin/env python3

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import builtins
import functools
import io
import json
import re
import signal
import sys
import textwrap
import urllib.parse
import urllib.request

import html2text

0_0  # Python >= 3.6 is required

# Let's trick http.client into writing debugging stuff to stderr, not stdout.
print = functools.partial(builtins.print, file=sys.stdout)  # pylint: disable=redefined-builtin
sys.stdout = sys.stderr

class UserAgent():

    headers = {
        'User-Agent': 'zygolophodon (https://github.com/jwilk/zygolophodon)',
    }
    debug_level = 0

    @classmethod
    def _build_opener(cls):
        # TODO: Get rid of this function once
        # <https://github.com/python/cpython/issues/99352> is fixed.
        handlers = [
            Handler(debuglevel=cls.debug_level)
            for Handler in [urllib.request.HTTPHandler, urllib.request.HTTPSHandler]
        ]
        return urllib.request.build_opener(*handlers)

    @classmethod
    def get(cls, url):
        headers = dict(cls.headers)
        request = urllib.request.Request(url, headers=headers)
        opener = cls._build_opener()
        return opener.open(request)

    @classmethod
    def get_json(cls, url):
        with cls.get(url) as fp:
            with io.TextIOWrapper(fp, encoding='UTF-8') as tfp:
                return json.load(tfp, object_hook=DictProxy)

wget = UserAgent.get
wget_json = UserAgent.get_json

class DictProxy(object):

    def __init__(self, d):
        self._d = d

    def __getattr__(self, attr):
        return self._d[attr]

def fmt_user(account):
    return f'{account.display_name} <{account.url}>'.lstrip()

def fmt_date(d):
    d = re.sub(r'[.]\d+', '', d)
    d = d.replace('T', ' ')
    return d

def fmt_html(html):
    html2md = html2text.HTML2Text()
    html2md.unicode_snob = True
    text = html2md.handle(html)
    return text.strip('\n')

def xmain():
    urls = ['@USER', '@USER/NNNNNN']
    urls = [f'https://DOMAIN/{url}' for url in urls]
    epilog = 'supported URLs:\n' + str.join('\n', [f'  {url}' for url in urls])
    ap = argparse.ArgumentParser(epilog=epilog, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--debug', action='store_true', help=argparse.SUPPRESS)
    ap.add_argument('url', metavar='URL')
    opts = ap.parse_args()
    if opts.debug:
        UserAgent.debug_level = 1
    url, _ = urllib.parse.urldefrag(opts.url)
    match = re.match(r'\Ahttps://([^/]+)/@([^/]+)(?:/([0-9]+)\Z)?', url)
    if not match:
        ap.error('unsupported URL')
    (domain, account, ident) = match.groups()
    if ident is None:
        process_user(domain, account)
    else:
        process_status(domain, ident)

def process_user(domain, account):
    api = f'https://{domain}/api/v1'
    q_account = urllib.parse.quote(account)
    user = wget_json(f'{api}/accounts/lookup?acct={q_account}')
    print('User:', fmt_user(user))
    print()
    print(fmt_html(user.note))
    url = f'{api}/accounts/{user.id}/statuses';
    statuses = wget_json(f'{url}?pinned=true')
    print_statuses(statuses, pinned=True)
    statuses = wget_json(f'{url}?exclude_replies=true')
    print_statuses(statuses)

def process_status(domain, ident):
    api = f'https://{domain}/api/v1'
    post = wget_json(f'{api}/statuses/{ident}')
    print_post(post)
    context = wget_json(f'{api}/statuses/{ident}/context')
    print_statuses(context.descendants)

def print_statuses(statuses, *, pinned=False):
    for post in statuses:
        print()
        print('-' * 72)
        print()
        print_post(post, pinned=pinned)

def normalize_lang(lang):
    if lang is None:
        return 'en'
    if lang.startswith('en-'):
        return 'en'
    return lang

def print_post(post, *, pinned=False):
    print('Location:', post.url)
    if pinned:
        print('Pinned: yes')
    print('From:', fmt_user(post.account))
    print('Date:', fmt_date(post.created_at))
    if normalize_lang(post.language) != 'en':
        print('Language:', post.language)
    if post.reblog:
        print('Reblog: yes')
    print()
    sep = ''
    for att in post.media_attachments or ():
        print('*', att.url)
        text = att.description
        if text:
            text = textwrap.indent(att.description, '  ')
            print()
            print(text)
        sep = '\n'
    if post.reblog:
        print(sep, end='')
        print_post(post.reblog)
    else:
        text = fmt_html(post.content)
        if text:
            print(sep, end='')
            print(text)

def main():
    try:
        xmain()
    except BrokenPipeError:
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
        signal.raise_signal(signal.SIGPIPE)
        raise

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
