#!/usr/bin/env python3

# Copyright © 2025 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import pathlib
import re
import sys
import types
import textwrap

int(0_0)  # Python >= 3.6 is required

here = pathlib.Path(__file__).parent
base = here.parent

def rextract(regexp, text, flags=0):
    regexp = re.compile(regexp, flags=flags)
    match = re.search(regexp, text)
    if match is None:
        raise LookupError(f'{regexp} not found')
    return match.group(1)

def addr_to_roff(addr, itype):
    out = re.sub('([A-Z]+)', r'\\f(BI\1\\fP', addr)
    out = f'.B {out}'
    if itype:
        out += f' \\fR({itype})'
    out = f'.IP \\(bu 2\n{out}'
    return out

charmap = r'''
' \(aq
` \`
“ \(lq
” \(rq
- \-
ä \[:a]
⋮ \&...
'''
charmap = {
    ord(key): value
    for line in charmap.strip().splitlines()
    for key, value in [line.split()]
}

def main():
    chunks = types.SimpleNamespace()
    code = (base / 'lib/cli.py').read_text(encoding='UTF-8')
    chunks.version = rextract(r"\b__version__ = '(.+)'", code)
    readme = (base / 'README').read_text(encoding='UTF-8')
    addrs = rextract(r'^ +ADDRESS(( +(\S.*\n))+)', readme, flags=re.M)
    roff_addrs = []
    for match in re.finditer(r'^ +(\S+)(?: [(](\S+)[)])?$', addrs, flags=re.M):
        addr, itype = match.groups()
        roff_addrs += [addr_to_roff(addr, itype)]
    chunks.address_list = str.join('\n', roff_addrs)
    try:
        example = rextract(r'(^ +[$] zygolophodon https:.+\n(( .*)?\n)+)', readme, flags=re.M)
    except LookupError:
        pass
    else:
        example = textwrap.dedent(example)
        example = re.sub('^([$] )(.*)', r'.RB "\1" "\2"', example)
        example = example.translate(charmap)
        example.encode('ASCII')
        chunks.example = example
    text = sys.stdin.read()
    def repl(match):
        name = match.group(1)
        name = name.lower().replace('-', '_')
        return getattr(chunks, name)
    text = re.sub(r'[{][{]([^\s}]+)[}][}]', repl, text)
    print(text)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
