name: CI
permissions: {}
on:
- push
- pull_request
jobs:

  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - python: '3.8'
          os: ubuntu-22.04
        - python: '3.9'
          os: ubuntu-22.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12'
          os: ubuntu-22.04
        - python: '3.13'
          os: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}
    - name: run tests
      run: |
        make test verbose=1
    - name: run network tests
      run: |
        prove -v t/network.t '::' --network
    - name: install
      run: |
        make install PREFIX=~/.local
    - name: post-install smoke-test
      run: |
        cd /
        zygolophodon --version
    - name: post-install man page check
      env:
        MANPATH: /home/runner/.local/share/man
        MANWIDTH: 80
      run: |
        cd /
        man 1 zygolophodon | grep -A 10 -w ZYGOLOPHODON
    - name: run post-install tests
      run: |
        rm zygolophodon doc/*.1 doc/*.1.in
        make test-installed verbose=1
        git restore .
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: run pylint
      run: |
        python3 -m pip install pylint
        python3 -m pylint $(grep -rl '/env python3$' .) lib/*.py
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

  nonpython:
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - ubuntu-24.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install perlcritic
      run: |
        sudo apt-get install libperl-critic-perl
    - name: run perlcritic
      run: |
        perlcritic $(grep -rl '/env perl$' .)
    - name: regenerate README
      run: |
        private/update-readme
        git diff --exit-code
    - name: install mandoc
      run: |
        sudo apt-get install mandoc
    - name: build man page
      run: |
        make doc/zygolophodon.1
    - name: run mandoc lint
      run: |
        mandoc -T lint doc/*.1

# vim:ts=2 sts=2 sw=2 et
